### ISSUE TITLE
TOF datatype

### ISSUE THREAD

**Issue by murty206** [Yveaux/TDC7200#1]
Hello Yveaux, thank you for the library of the TDC7200, I need to know what is the returned value of readMeasurement function in your library is it microseconds? Also I need to do some math on returned TOF data but since it is declared as uint64_t I cannot do anything with the returned number all I can do is printing value to serial port as in your example? Could you help me with that issue? Thank you.

**Comment by Yveaux** [comment]
Returned tof is in picoseconds, hence the 64bit type.
You could use either of the low or high 32bits from the 64bit value, shift it to reduce resolution or convert to double. It all depends on your use case.

**Comment by murty206** [comment]
Thank you for your answer it helps a lot,
