### ISSUE TITLE
Calib1 and 2 do not change - still at 0

### ISSUE THREAD

**Issue by kelu124** [Yveaux/TDC7200#2]
Salut @Yveaux 
Thanks for the great work on the TDC7200 lib =)
I've been using it and works well with the example you shared - however, the calibration registers 1 and 2 are still set to 0 in my case -- (used with a [HC SR04 to have a better view of the pulses - ino's there ](https://github.com/kelu124/TDC7k2_HCSr04/blob/891975ec7c8501bccb5d5dcb344ed8040b71f452/main/main.ino)).
Because Calib1 and 2 are not set, normLSB does not get set properly.
I have basically made a copy paste of your code, but it seems not to work - would you have any hints there?
Many thanks in advance!

**Comment by Yveaux** [comment]
It's been a while since I actively developed on the TDC7200 lib and I don't have a setup currently to test your claim.
I you were to provide a PR fixing the issue, I'm happy to take it in.

**Comment by kelu124** [comment]
Salut ! Thanks for this. I'm new to this chip, and happy to open a PR once I find the source of the issue.
In a nutshell, it is not clear for me from the datasheet, but when are the registers of the calibration values 1 and 2 (used I assume to compensate for internal drifts) written by the TDC?
When using the lib as is, I'm getting a crash because there a division by (Calib2 - Calib) that just crashes.
Anyhow, will have another look at what I may be missing!
